// <auto-generated />
namespace Infinite.MVC.Day2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AlterProductName_Varchar50 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterProductName_Varchar50));
        
        string IMigrationMetadata.Id
        {
            get { return "202301171707282_AlterProductName_Varchar50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
